//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Codeunit/BalanceWarehouse")]
        public string WindowsFormsApplication1_WarehouseService_BalanceWarehouse {
            get {
                return ((string)(this["WindowsFormsApplication1_WarehouseService_BalanceWarehouse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/WarehouseEmployee")]
        public string WindowsFormsApplication1_WSWarehouseEmployee_WarehouseEmployee_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSWarehouseEmployee_WarehouseEmployee_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/WhseReceiptList")]
        public string WindowsFormsApplication1_WSWarehouseReceipts_WhseReceiptList_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSWarehouseReceipts_WhseReceiptList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/PurchaseOrderCard")]
        public string WindowsFormsApplication1_WSPurchaseOrderCard_PurchaseOrderCard_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSPurchaseOrderCard_PurchaseOrderCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/WarehouseReceiptLine")]
        public string WindowsFormsApplication1_WSWarehouseReceiptLines_WarehouseReceiptLine_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSWarehouseReceiptLines_WarehouseReceiptLine_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/PurchaseOrderList")]
        public string WindowsFormsApplication1_WSPurchaseOrderList_PurchaseOrderList_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSPurchaseOrderList_PurchaseOrderList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/DetailedUserInformation")]
        public string WindowsFormsApplication1_WSDetailedUserInformation_DetailedUserInformation_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSDetailedUserInformation_DetailedUserInformation_Servic" +
                    "e"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/UserInformation")]
        public string WindowsFormsApplication1_WSUserInformation_UserInformation_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSUserInformation_UserInformation_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/ItemBinContent")]
        public string WindowsFormsApplication1_WSItemBinContent_ItemBinContent_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSItemBinContent_ItemBinContent_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/BinContent")]
        public string WindowsFormsApplication1_WSBinContent_BinContent_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSBinContent_BinContent_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/PickList")]
        public string WindowsFormsApplication1_WSPickList_PickList_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSPickList_PickList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/PickLines")]
        public string WindowsFormsApplication1_WSPickLines_PickLines_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSPickLines_PickLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/TerminalPrinterList")]
        public string WindowsFormsApplication1_TerminalPrinterList_TerminalPrinterList_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_TerminalPrinterList_TerminalPrinterList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/SalesOrderHeader")]
        public string WindowsFormsApplication1_WSSalesOrderHeader_SalesOrderHeader_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSSalesOrderHeader_SalesOrderHeader_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/SalesOrderLine")]
        public string WindowsFormsApplication1_WSSalesOrderLine_SalesOrderLine_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSSalesOrderLine_SalesOrderLine_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/WarehouseShipmentFright")]
        public string WindowsFormsApplication1_WSWarehouseFright_WarehouseShipmentFright_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSWarehouseFright_WarehouseShipmentFright_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/WarehouseShipmentList")]
        public string WindowsFormsApplication1_WSWhseShipHeaderList_WarehouseShipmentList_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSWhseShipHeaderList_WarehouseShipmentList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/ItemListPage")]
        public string WindowsFormsApplication1_WSItemList_ItemListPage_Service {
            get {
                return ((string)(this["WindowsFormsApplication1_WSItemList_ItemListPage_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/SalesCommentLines")]
        public string Balance_Warehouse_WSSalesCommentLines_SalesCommentLines_Service {
            get {
                return ((string)(this["Balance_Warehouse_WSSalesCommentLines_SalesCommentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/SalesReturnOrder")]
        public string BalanceWarehouse_WSSalesReturnOrder_SalesReturnOrder_Service {
            get {
                return ((string)(this["BalanceWarehouse_WSSalesReturnOrder_SalesReturnOrder_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.34.0.15:7047/DRIFT/WS/AKUDIM/Page/TestItem")]
        public string BalanceWarehouse_WSTestItemList_TestItem_Service {
            get {
                return ((string)(this["BalanceWarehouse_WSTestItemList_TestItem_Service"]));
            }
        }
    }
}
